name: Mirror and run GitLab CI

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/ThanhTruong2311/dtuserversocket.git"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "ThanhTruong2311"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # GitLab Personal Access Token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}